env:
  browser: true
  commonjs: true
  es6: true
plugins:
  - react
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
    - varsIgnorePattern: _+$
  no-console:
    - warn
  max-len:
    - warn
    - code: 80
    - ignoreComments: false
    - ignoreStrings: false
