env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console:
    - warn
  max-len:
    - warn
    - code: 80
    - ignoreComments: false
    - ignoreStrings: false
