fragment Commit on Commit {
  oid
  author {
    date
    email
    name
  }
  message
  messageBody
  tree {
    entries {
      name
      oid
    }
  }
}

fragment File on TreeEntry {
  name
  object {
    ... on Blob {
      text
    }
  }
}

query getCommitBySha($user: String!, $repository: String!, $sha: String!) {
  repository(owner: $user, name: $repository) {
    object(expression: $sha) {
      ... on Commit {
        ...Commit
      }
    }
  }
}

query getCommitByOid($user: String!, $repository: String!, $oid: String!) {
  repository(owner: $user, name: $repository) {
    object(oid: $oid) {
      ... on Commit {
        ...Commit
      }
    }
  }
}

query getFileByOid($user: String!, $repository: String!, $oid: GitObjectID) {
  repository(owner: $user, name: $repository) {
    object(oid: $oid) {
      ... on Blob {
        text
      }
    }
  }
}
